# Generated by Django 3.1.4 on 2021-01-03 01:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_iban.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regularity', models.CharField(choices=[('Y', 'Yearly'), ('M', 'Monthly'), ('W', 'Weekly'), ('D', 'Daily')], default='M', max_length=1)),
                ('is_regular', models.BooleanField()),
                ('due_date', models.DateField()),
                ('is_paid', models.BooleanField(default=False)),
                ('invoice_type', models.CharField(choices=[('WEB', 'Website'), ('FIL', 'File'), ('CRD', 'Credentials')], max_length=3)),
                ('website', models.URLField(blank=True)),
                ('login', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(blank=True, upload_to='user_files')),
                ('iban', django_iban.fields.IBANField(blank=True, enforce_database_constraint=False, max_length=34)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=9)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_class', models.CharField(choices=[('MR', 'Moderator'), ('MG', 'Manager'), ('CL', 'Client')], max_length=2)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('managed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='invoices_system.user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now)),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_logs', to='invoices_system.invoice')),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_invoices', to='invoices_system.user')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices_system.user'),
        ),
    ]
