# Generated by Django 3.1.4 on 2021-01-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices_system', '0001_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='My invoice', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_class',
            field=models.CharField(choices=[('MR', 'Moderator'), ('MG', 'Manager'), ('CL', 'Client')], default='CL', max_length=2),
        ),
    ]
